Updating the update command so that it first tries to run lbin and lpython to find pip and python before falling back on the system path.

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -1,15 +1,49 @@
 #!/bin/sh
 
+# Defer to a PYTHON environment variable first, otherwise try to use
+# lpython (for finding a local virtualenv, otherwise fal back on the
+# system python
+if test -z "$PYTHON"; then
+    PYTHON=`lpython -c 'import sys; sys.stdout.write(sys.executable)'`
+fi
+if test -z "$PYTHON"; then
+    PYTHON=`python -c 'import sys; sys.stdout.write(sys.executable)'`
+fi
+if test -n "$PYTHON"; then
+    echo "Using python $PYTHON"
+else
+    echo "ERROR: Cannot find python."
+    echo "Please set PYTHON envronment variable or add to PATH"
+    exit 1
+fi
+
+# Defer to a PYTHON_PIP environment variable first, otherwise try to use
+# lpython (for finding a local virtualenv, otherwise fal back on the
+# system python
+if test -z "$PYTHON_PIP"; then
+    PYTHON_PIP=`lbin -f pip | head -1`
+fi
+if test -z "$PYTHON_PIP"; then
+    PYTHON_PIP=`which pip | head -1`
+fi
+if test -n "$PYTHON_PIP"; then
+    echo "Using pip $PYTHON_PIP"
+else
+    echo "ERROR: Cannot find pip."
+    echo "Please set PYTHON_PIP envronment variable or add to PATH"
+    exit 1
+fi
+
 if [ 1 ]; then
     # Install wheel if it's not already available
-    pip install wheel
+    $PYTHON_PIP install wheel
 
     # Clone virtualenv git repo
     rm -Rf virtualenv_git
     git clone https://github.com/pypa/virtualenv.git virtualenv_git
 
     # Create a wheel file for virtualenv
-    pip wheel --wheel-dir virtualenv_git/virtualenv_support virtualenv
+    $PYTHON_PIP wheel --wheel-dir virtualenv_git/virtualenv_support virtualenv
 
     # Move virtualenv_support into ../pyutilib/virtualenv
     rm -Rf ./virtualenv_support
@@ -20,8 +54,8 @@ fi
 zip -r virtualenv_support.zip virtualenv_support
 
 # Fill the template with the ZIP file
-python `dirname $0`/rebuild.py wheels_template.py wheels.py
+$PYTHON `dirname $0`/rebuild.py wheels_template.py wheels.py
 cp wheels.py ../pyutilib/virtualenv
 
 # Generate ../pyutilib/virtualenv/vpy_install.py
-python update.py
+$PYTHON update.py
